const r = await fetch("http://127.0.0.1:9222/json/new?" + encodeURIComponent(process.argv[2]), {method:"PUT"});
const t = await r.json();
const ws = new WebSocket(t.webSocketDebuggerUrl);
let id = 0; const pending = new Map();
const send = (method, params={}) => new Promise(res => { const i = ++id; pending.set(i, res); ws.send(JSON.stringify({id:i, method, params})); });
ws.onmessage = (e) => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m.result); pending.delete(m.id); } };
await new Promise(res => ws.onopen = res);
await send("Emulation.setDeviceMetricsOverride", {width:375, height:800, deviceScaleFactor:1, mobile:true});
await send("Page.enable");
await new Promise(r => setTimeout(r, 2500));
const js = `(() => {
  const d = document.documentElement;
  const pma = [...document.querySelectorAll('span')].filter(e => /%$/.test(e.textContent||''));
  const fuori = pma.filter(e => e.getBoundingClientRect().right > 375.5).length;
  const nomi = [...document.querySelectorAll('span.truncate')].map(e => Math.round(e.getBoundingClientRect().width));
  return JSON.stringify({scrollWidth: d.scrollWidth, pmaTotali: pma.length, pmaFuoriSchermo: fuori, nomePiuLargo: Math.max(...nomi)}, null, 1);
})()`;
const out = await send("Runtime.evaluate", {expression: js, returnByValue: true});
console.log(out.result?.value ?? JSON.stringify(out));
await fetch(`http://127.0.0.1:9222/json/close/${t.id}`);
process.exit(0);
